# Generated by Django 6.1.1 on 2026-09-04 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('detecting', 'Detecting spills...'), ('drifting', 'Computing drift...'), ('scoring', 'Scoring vessels...'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('spills_detected', models.IntegerField(default=0)),
                ('suspects_ranked', models.IntegerField(default=0)),
                ('wind_speed_mps', models.FloatField(default=5.0)),
                ('wind_direction_deg', models.FloatField(default=180.0)),
                ('current_speed_mps', models.FloatField(default=0.3)),
                ('current_direction_deg', models.FloatField(default=90.0)),
                ('drift_duration_hours', models.FloatField(default=24.0)),
                ('detection_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_run', to='detection.detectionjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
