# Generated by Django 6.1.1 on 2026-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(blank=True, default='queued', max_length=50),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='stage_durations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
