# Generated by Django 6.1.1 on 2026-09-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_pipelinerun_image_path_pipelinerun_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='is_georeferenced',
            field=models.BooleanField(default=False),
        ),
    ]
