# Generated by Django 6.1.1 on 2026-09-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_pipelinerun_is_georeferenced'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='bbox_max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='bbox_max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='bbox_min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='bbox_min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
