# Generated by Django 6.1.1 on 2026-09-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_pipelinerun_bbox_max_lat_pipelinerun_bbox_max_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='metocean_source',
            field=models.CharField(blank=True, default='default_fallback', max_length=50),
        ),
    ]
