# Generated by Django 6.1.1 on 2026-09-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_pipelinerun_metocean_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='attribution_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='evidence_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='manifest_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='regions_rejected_as_lookalike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='unknown_vessel_posterior',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
