# Generated by Django 6.1.1 on 2026-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_pipelinerun_attribution_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='robustness_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
