# Generated by Django 6.1.1 on 2026-09-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_pipelinerun_robustness_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='submitted_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='submitted_by_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
