# Generated by Django 6.1.1 on 2026-09-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spillregion',
            name='centroid_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spillregion',
            name='centroid_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
