# Generated by Django 6.1.1 on 2026-09-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_spillregion_centroid_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spillregion',
            name='lookalike_contributions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spillregion',
            name='lookalike_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spillregion',
            name='lookalike_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='spillregion',
            name='lookalike_verdict',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='spillregion',
            name='oil_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spillregion',
            name='shape_complexity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spillregion',
            name='volume_estimate',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
