# Generated by Django 6.1.1 on 2026-09-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_used', models.CharField(max_length=50)),
                ('origin_lat', models.FloatField()),
                ('origin_lon', models.FloatField()),
                ('origin_time', models.DateTimeField()),
                ('origin_uncertainty_km', models.FloatField(default=5.0)),
                ('hindcast_trajectory', models.JSONField(default=list)),
                ('forecast_trajectory', models.JSONField(default=list)),
                ('wind_speed_mps', models.FloatField()),
                ('wind_direction_deg', models.FloatField()),
                ('current_speed_mps', models.FloatField()),
                ('current_direction_deg', models.FloatField()),
                ('duration_hours', models.FloatField(default=24.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spill_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_results', to='detection.spillregion')),
            ],
        ),
    ]
