# Generated by Django 6.1.1 on 2026-09-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftresult',
            name='metocean_source',
            field=models.CharField(blank=True, default='default_fallback', max_length=50),
        ),
    ]
