# Generated by Django 6.1.1 on 2026-09-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0002_driftresult_metocean_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftresult',
            name='confidence_polygon_50',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='confidence_polygon_90',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='ensemble_seed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='evaporated_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='metocean_degraded_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='n_particles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='origin_particles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='radius_50_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='radius_90_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driftresult',
            name='weathering_warning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
