# Generated by Django 6.1.1 on 2026-09-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(db_index=True, max_length=9, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('vessel_type', models.CharField(blank=True, default='', max_length=100)),
                ('flag', models.CharField(blank=True, default='', max_length=50)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('width_m', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximity_score', models.FloatField()),
                ('temporal_score', models.FloatField()),
                ('behavioral_score', models.FloatField()),
                ('composite_score', models.FloatField()),
                ('min_distance_km', models.FloatField()),
                ('closest_time', models.DateTimeField()),
                ('anomalies_detected', models.JSONField(default=list)),
                ('rank', models.IntegerField(default=0)),
                ('drift_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_scores', to='drift.driftresult')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_scores', to='ais.vessel')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('drift_result', 'vessel')},
            },
        ),
        migrations.CreateModel(
            name='AISRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed_knots', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ais_records', to='ais.vessel')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'lat', 'lon'], name='ais_aisreco_timesta_29bd63_idx'), models.Index(fields=['vessel', 'timestamp'], name='ais_aisreco_vessel__0d0f5b_idx')],
            },
        ),
    ]
