# Generated by Django 6.1.1 on 2026-09-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectscore',
            name='behavioural_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='cpa_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='cpa_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='explanation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='posterior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='spatiotemporal_likelihood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='verdict',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
