# Generated by Django 6.1.1 on 2026-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0002_suspectscore_behavioural_factor_suspectscore_cpa_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectscore',
            name='integrity_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='integrity_plausible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suspectscore',
            name='max_implied_speed_kn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
